djadhere/urls.py
from django.conf import settings
from django.contrib.gis import admin
from django.urls import include, path

urlpatterns = [
    path("accounts/", include("accounts.urls")),
    path("todo/", include("todo.urls")),
    path("", include("services.urls")),
    path("", include("adhesions.urls")),
    path("", include("banking.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]


admin.site.site_title = settings.SITE_TITLE
admin.site.site_header = settings.SITE_HEADER

todo/urls.py
from django.urls import path

from . import views

app_name = "todo"


urlpatterns = [
    path("", views.tasklist_list, name="list-tasklists"),
    path("<str:tasklist_slug>/", views.tasklist_detail, name="show-tasklist"),
    path(
        "<str:tasklist_slug>/completed/",
        views.tasklist_detail,
        {"completed": True},
        name="show-tasklist-completed",
    ),
    path(
        "<str:tasklist_slug>/reorder/",
        views.tasklist_reorder,
        name="reorder-tasklist",
    ),
    path(
        "<str:tasklist_slug>/subscribe/",
        views.tasklist_subscribe,
        {"subscribe": True},
        name="subscribe-tasklist",
    ),
    path(
        "<str:tasklist_slug>/unsubscribe/",
        views.tasklist_subscribe,
        {"subscribe": False},
        name="unsubscribe-tasklist",
    ),
    path("<str:tasklist_slug>/add/", views.task_form, name="add-task"),
    path("<str:tasklist_slug>/<int:task_id>/", views.task_detail, name="show-task"),
    path(
        "<str:tasklist_slug>/<int:task_id>/toggle-done/",
        views.task_toggle_done,
        name="toggle-task-done",
    ),
    path(
        "<str:tasklist_slug>/<int:task_id>/subscribe/",
        views.task_subscribe,
        {"subscribe": True},
        name="subscribe-task",
    ),
    path(
        "<str:tasklist_slug>/<int:task_id>/unsubscribe/",
        views.task_subscribe,
        {"subscribe": False},
        name="unsubscribe-task",
    ),
    path("<str:tasklist_slug>/<int:task_id>/edit/", views.task_form, name="edit-task"),
    path(
        "<str:tasklist_slug>/<int:task_id>/delete/",
        views.task_delete,
        name="delete-task",
    ),
]

djadhere/templates/_form.html
{% load bootstrap4 %}
<form action="" method="post" class="form-horizontal"{% if multipart %} enctype=multipart/form-data{% endif %}>
  {% csrf_token %}
  {% block beforeform %}{% endblock %}
  {% if form %}
  {% bootstrap_form form layout="horizontal" %}
  {% endif %}
  {% for form in forms %}
  {% bootstrap_form form layout="horizontal" %}
  {% endfor %}
  {% buttons layout="horizontal" %}
  <button type="submit" class="btn btn-primary">Envoyer</button>
  {% for url, class, text in buttons %}
  <a href="{% url url %}" class="btn btn-{{ class }}">{{ text }}</a>
  {% endfor %}
  {% if request.META.HTTP_REFERER %}<a href="{{ request.META.HTTP_REFERER }}" class="btn btn-default">Annuler</a>{% endif %}
  {% endbuttons %}
</form>

djadhere/templates/base.html
{% load static bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="tetaneutral.net">

    <title>{% block title %}tetaneutral.net{% endblock %}</title>

    {% block css %}
    {% bootstrap_css %}
    <link href="{% static 'css/djadhere.css' %}" rel="stylesheet">
    {{ form.media.css }}
    {% endblock %}

    {% block js %}
    {% bootstrap_javascript jquery="full" %}
    <script defer src="https://use.fontawesome.com/releases/v5.8.1/js/all.js" integrity="sha384-g5uSoOSBd7KkhAMlnQILrecXvzst9TdC09/VM+pjDTCM+1il8RHz5fKANTFFb+gQ" crossorigin="anonymous"></script>
    {% endblock %}

    {% block extrahead %}{% endblock extrahead %}
    {% block extra_js %}{% endblock extra_js %}
  </head>

  <body>
{% block pageheader %}
  <header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="#">tetaneutral.net</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop" aria-expanded="false" aria-controls="navbarTop" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div id="navbarTop" class="navbar-collapse collapse">
        <ul class="navbar-nav mr-auto">
          {% if request.user.is_authenticated %}
          <li class="nav-item{% block usertab %}{% endblock %}">
            <a class="nav-link" href="{% url 'adhesion-detail' %}">
              <span class="fas fa-heart"></span>&nbsp;Mon adhésion
            </a>
          </li>
          {% for corp in request.corporations %}
          {% if forloop.first %}
          <li class="nav-item dropdown{% block corptab %}{% endblock %}">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <span class="fas fa-globe-europe"></span>&nbsp;Mes associations <span class="caret"></span>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% endif %}
              <a class="dropdown-item" href="{% url 'corporation-detail' corp.object.pk %}">{{ corp.object.social_reason }}</a>
          {% if forloop.last %}
            </div>
          </li>
          {% endif %}
          {% endfor %}
          <li class="nav-item{% block todotab %}{% endblock %}">
            <a class="nav-link" href="{% url 'todo:list-tasklists' %}">
              <span class="fas fa-tasks"></span>&nbsp;Liste des tâches
            </a>
          </li>
          {% endif %}
          <li class="nav-item dropdown{% block transparencetab %}{% endblock %}">
            <a class="nav-link dropdown-toggle" href="#" id="TransparenceDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="fas fa-coins"></span>&nbsp;Transparence
            </a>
            <div class="dropdown-menu" aria-labelledby="TransparenceDropdown">
              <a class="dropdown-item" href="{% url 'income' %}"><span class="fas fa-plus"></span>&nbsp;Recettes</a>
              <a class="dropdown-item" href="{% url 'outcome' %}"><span class="fas fa-minus"></span>&nbsp;Dépenses</a>
              <a class="dropdown-item" href="{% url 'balance' %}"><span class="fas fa-euro-sign"></span>&nbsp;Solde</a>
            </div>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item{% block statustab %}{% endblock %}">
            <a class="nav-link" href="{% url 'status' %}">
              <span class="fas fa-bullhorn"></span>&nbsp;Status
            </a>
          </li>
          {% endif %}
        </ul>
        <ul class="navbar-nav">
          {% if request.user.is_authenticated %}
          {% if request.user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}"><span class="fas fa-user-cog"></span>&nbsp;Administration</a>
          </li>
          {% endif %}
          <li class="nav-item"{% block profiletab %}{% endblock %}>
            <a class="nav-link" href="{% url 'profile' %}">
              <span class="fas fa-user"></span>&nbsp;Profil
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}" data-toggle="tooltip" data-placement="bottom" title="Logout">
              <span class="fas fa-sign-out-alt"></span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}" data-toggle="tooltip" data-placement="bottom" title="Login">
              <span class="fas fa-sign-in-alt"></span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
{% endblock %}

{% block container %}
	<main class="container">
      {% block breadcrumbol %}{% endblock %}
      {% bootstrap_messages %}
{% block content %}{% endblock %}
    </main>
{% endblock %}

{% block pagefooter %}
    <footer class="footer">
      <div class="container">
        <span class="text-muted">Propulsé par <a href="https://code.ffdn.org/tetaneutral.net/djadhere">djadhere</a></span>
      </div>
    </footer>
{% endblock %}

    {% block js_end %}
    <script src="{% static 'js/djadhere.js' %}"></script>
	{{ form.media.js }}
    {% endblock %}
  </body>
</html>