banking/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("transparence/income/", views.income, name="income"),
    path("transparence/outcome/", views.outcome, name="outcome"),
    path("transparence/balance/", views.balance, name="balance"),
]

djadhere/urls.py
from django.conf import settings
from django.contrib.gis import admin
from django.urls import include, path

urlpatterns = [
    path("accounts/", include("accounts.urls")),
    path("todo/", include("todo.urls")),
    path("", include("services.urls")),
    path("", include("adhesions.urls")),
    path("", include("banking.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]


admin.site.site_title = settings.SITE_TITLE
admin.site.site_header = settings.SITE_HEADER

todo/urls.py
from django.urls import path

from . import views

app_name = "todo"


urlpatterns = [
    path("", views.tasklist_list, name="list-tasklists"),
    path("<str:tasklist_slug>/", views.tasklist_detail, name="show-tasklist"),
    path(
        "<str:tasklist_slug>/completed/",
        views.tasklist_detail,
        {"completed": True},
        name="show-tasklist-completed",
    ),
    path(
        "<str:tasklist_slug>/reorder/",
        views.tasklist_reorder,
        name="reorder-tasklist",
    ),
    path(
        "<str:tasklist_slug>/subscribe/",
        views.tasklist_subscribe,
        {"subscribe": True},
        name="subscribe-tasklist",
    ),
    path(
        "<str:tasklist_slug>/unsubscribe/",
        views.tasklist_subscribe,
        {"subscribe": False},
        name="unsubscribe-tasklist",
    ),
    path("<str:tasklist_slug>/add/", views.task_form, name="add-task"),
    path("<str:tasklist_slug>/<int:task_id>/", views.task_detail, name="show-task"),
    path(
        "<str:tasklist_slug>/<int:task_id>/toggle-done/",
        views.task_toggle_done,
        name="toggle-task-done",
    ),
    path(
        "<str:tasklist_slug>/<int:task_id>/subscribe/",
        views.task_subscribe,
        {"subscribe": True},
        name="subscribe-task",
    ),
    path(
        "<str:tasklist_slug>/<int:task_id>/unsubscribe/",
        views.task_subscribe,
        {"subscribe": False},
        name="unsubscribe-task",
    ),
    path("<str:tasklist_slug>/<int:task_id>/edit/", views.task_form, name="edit-task"),
    path(
        "<str:tasklist_slug>/<int:task_id>/delete/",
        views.task_delete,
        name="delete-task",
    ),
]

services/models.py
from base64 import urlsafe_b64encode
from datetime import timedelta
from hashlib import sha256
from ipaddress import IPv4Address, IPv6Address, ip_network
from urllib.parse import quote

from django.apps import apps
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils import timezone
from django.utils.html import mark_safe

from banking.models import RecurringPayment
from djadhere.utils import get_active_filter, is_overlapping

from .utils.ip_conversion import ipv4_to_ipv6, ipv6_to_ipv4


def ipprefix_validator(value):
    try:
        ip_network(value)
    except ValueError as err:
        msg = "%s n`est pas un préfixe valide" % value
        raise ValidationError(msg) from err


class IPPrefix(models.Model):
    prefix = models.CharField(
        max_length=128,
        verbose_name="Préfixe",
        validators=[ipprefix_validator],
        unique=True,
    )

    class Meta:
        ordering = ["prefix"]
        verbose_name = "Réseau"
        verbose_name_plural = "Réseaux"

    def __str__(self):
        return self.prefix


class IPResourceManager(models.Manager):
    def get_queryset(self):
        qs = super().get_queryset()
        # On rajoute une super annotation « in_use » pour savoir si l`IP est dispo ou
        # non :-)
        return qs.annotate(
            in_use=models.Exists(
                ServiceAllocation.objects.filter(
                    Q(resource=models.OuterRef("pk")) & get_active_filter(),
                ),
            ),
        )
        # Ouf, pas de duplication car l`IP ne peut être utilisé que par un seul service!


class ActiveAllocationManager(models.Manager):
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.annotate(
            active=models.Case(
                models.When(get_active_filter(), then=True),
                default=False,
                output_field=models.BooleanField(),
            ),
        )


class ActiveServiceManager(models.Manager):
    def get_queryset(self):
        qs = super().get_queryset()
        one_year_ago = timezone.now() - timedelta(days=365)
        return qs.annotate(
            active=models.Exists(
                ServiceAllocation.objects.filter(
                    Q(service=models.OuterRef("pk")) & get_active_filter(),
                ),
            ),
            allocations_long_stopped=~models.Exists(
                ServiceAllocation.objects.filter(
                    Q(service=models.OuterRef("pk"))
                    & (Q(end__isnull=True) | Q(end__gte=one_year_ago)),
                ),
            ),
            contribution_long_stopped=models.Exists(
                RecurringPayment.objects.filter(
                    service=models.OuterRef("pk"),
                    long_stopped=True,
                ),
            ),
            long_stopped=models.Case(
                models.When(contribution__isnull=True, then=False),
                models.When(contribution_long_stopped=False, then=False),
                models.When(allocations_long_stopped=False, then=False),
                default=True,
                output_field=models.BooleanField(),
            ),
        )


class IPResource(models.Model):
    CATEGORY_PUBLIC = 0
    CATEGORY_ANTENNA = 1
    CATEGORIES = (
        (CATEGORY_PUBLIC, "IP Public"),
        (CATEGORY_ANTENNA, "IP Antenne"),
    )

    ip = models.GenericIPAddressField(verbose_name="IP", primary_key=True)
    prefixes = models.ManyToManyField(IPPrefix, verbose_name="préfixes")
    reserved = models.BooleanField(default=False, verbose_name="réservée")
    category = models.IntegerField(choices=CATEGORIES, verbose_name="catégorie")
    checkmk_label = models.CharField(max_length=128, blank=True, default="")
    last_state_old = models.ForeignKey(
        "IPResourceStateOld",
        on_delete=models.PROTECT,
        related_name="+",
        verbose_name="dernier état",
        null=True,
    )
    last_state = models.ForeignKey(
        "IPResourceState",
        null=True,
        on_delete=models.PROTECT,
        related_name="+",
        verbose_name="dernier état",
    )
    last_state_up = models.ForeignKey(
        "IPResourceState",
        null=True,
        on_delete=models.PROTECT,
        related_name="+",
        verbose_name="dernier état UP",
    )
    last_time_up = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name="Dernière réponse au ping",
    )

    objects = IPResourceManager()

    @property
    def allocations(self):
        return self.service_allocations if self.category == self.CATEGORY_PUBLIC else []

    @property
    def checkmk_url(self):
        if self.checkmk_label:
            return mark_safe(
                settings.CHECK_MK_URL.format(host=quote(self.checkmk_label)),
            )
        return None

    def password(self):
        data = sha256((settings.MASTER_PASSWORD + self.ip).encode("utf-8")).digest()
        return urlsafe_b64encode(data).decode("utf-8")[:8]

    password.short_description = "Mot de passe"

    def v4(self):
        if "." in self.ip:
            return IPv4Address(self.ip)
        # TODO: v6 only ?
        return ipv6_to_ipv4(self.v6())

    def v6(self):
        if ":" in self.ip:
            return IPv6Address(self.ip)
        return ipv4_to_ipv6(self.v4())

    class Meta:
        ordering = ["ip"]
        verbose_name = "IP"
        verbose_name_plural = "IP"

    def __str__(self):
        return str(self.ip)


class IPResourceStateCheck(models.Model):
    date = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["date"]

    def __str__(self):
        return str(self.date)


class IPResourceState(models.Model):
    STATE_DOWN = 0
    STATE_UP = 1
    STATE_CHOICES = (
        (STATE_DOWN, "DOWN"),
        (STATE_UP, "UP"),
    )
    ip = models.ForeignKey(
        IPResource,
        on_delete=models.CASCADE,
        related_name="state_set",
    )
    state = models.IntegerField(choices=STATE_CHOICES)
    begin = models.ForeignKey(
        IPResourceStateCheck,
        on_delete=models.PROTECT,
        related_name="+",
    )
    end = models.ForeignKey(
        IPResourceStateCheck,
        on_delete=models.PROTECT,
        related_name="+",
    )

    def __str__(self):
        return self.get_state_display()


class IPResourceStateOld(models.Model):
    STATE_DOWN = 0
    STATE_UP = 1
    STATE_UNKNOWN = 2
    STATE_CHOICES = (
        (STATE_DOWN, "DOWN"),
        (STATE_UP, "UP"),
        (STATE_UNKNOWN, "Inconnu"),
    )
    ip = models.ForeignKey(
        IPResource,
        on_delete=models.CASCADE,
        related_name="old_state_set",
    )
    date = models.DateTimeField(default=timezone.now)
    state = models.IntegerField(choices=STATE_CHOICES)

    def __str__(self):
        return self.get_state_display()


class ServiceType(models.Model):
    name = models.CharField(max_length=64, verbose_name="Nom", unique=True)
    contact = models.CharField(
        max_length=64,
        verbose_name="Contact en cas de problème",
        blank=True,
        default="",
    )

    class Meta:
        ordering = ["name"]
        verbose_name = "type de service"
        verbose_name_plural = "types de service"

    def __str__(self):
        return self.name


class Service(models.Model):
    """
    En cas d`ajout de champs, penser à mettre à jour la méthode save_model de
    ServiceAdmin.
    """

    adhesion = models.ForeignKey(
        "adhesions.Adhesion",
        verbose_name="Adhérent·e",
        related_name="services",
        on_delete=models.CASCADE,
    )
    service_type = models.ForeignKey(
        ServiceType,
        related_name="services",
        verbose_name="Type de service",
        on_delete=models.PROTECT,
    )
    label = models.CharField(blank=True, default="", max_length=128)
    notes = models.TextField(blank=True, default="")
    created = models.DateTimeField(auto_now_add=True)
    loan_equipment = models.BooleanField(default=False, verbose_name="Matériel en prêt")

    # WireGuard
    wireguard_pubkey = models.CharField(
        max_length=64,
        verbose_name="Clé public WireGuard",
        blank=True,
        default="",
    )

    contribution = models.OneToOneField(RecurringPayment, on_delete=models.CASCADE)

    objects = ActiveServiceManager()

    def save(self, *args, **kwargs):
        if not hasattr(self, "contribution"):
            self.contribution = RecurringPayment.objects.create()
        super().save(*args, **kwargs)

    def clean(self):
        super().clean()
        # Vérification de l`unicité par type de service du label
        if self.label != "" and Service.objects.exclude(pk=self.pk).filter(
            service_type=self.service_type,
            label=self.label,
        ):
            msg = "Un service du même type existe déjà avec ce label."
            raise ValidationError(msg)

    def is_active(self):
        return any(allocation.is_active() for allocation in self.allocations.all())

    is_active.boolean = True
    is_active.short_description = "Actif"

    @property
    def active_allocations(self):
        return self.allocations.filter(get_active_filter())

    @property
    def inactive_allocations(self):
        return self.allocations.exclude(get_active_filter())

    def get_absolute_url(self):
        return reverse(
            f"admin:{self._meta.app_label}_{self._meta.model_name}_change",
            args=(self.pk,),
        )

    def __str__(self):
        s = "#%d %s" % (self.pk, self.service_type)
        if self.label:
            s += " " + self.label
        return s


class Route(models.Model):
    name = models.CharField(max_length=64, unique=True)

    class Meta:
        ordering = ["name"]

    def get_ip(self):

banking/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from .models import Payment


class PaymentForm(ModelForm):
    class Meta:
        model = Payment
        fields = ["amount", "period", "payment_method", "start"]

    def clean_start(self):
        start = self.cleaned_data["start"]
        if self.instance.pk:
            if start < self.instance.start:
                msg = "valeur invalide"
                raise ValidationError(msg, code="invalid")
        return start

banking/templates/banking/admin/debtor.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
&rsaquo; <a href="{% url 'admin:banking_paymentupdate_changelist' %}">Paiements</a>
&rsaquo; <a href="{% url opts|admin_urlname:'change' payment.pk %}">{{ payment|truncatewords:"18" }}</a>
&rsaquo; Débiteur
</div>
{% endblock %}

{% block content %}

<ul>
  <li><b>Type :</b> {{ adhesion.type }}</li>
{% if adhesion.is_physical %}
  <li><b>Nom :</b> {{ adherent.last_name }}</li>
  <li><b>Prénom :</b> {{ adherent.first_name }}</li>
{% else %}
  <li><b>Raison sociale :</b> {{ adherent }}</li>
{% endif %}
  <li><b>Numéro d’adhérent·e :</b> <a href="{% url 'admin:adhesions_adhesion_change' adhesion.pk %}">{{ adhesion }}</a></li>
  <li><b>IBAN :</b> non implémenté, voir pad…</li>
  <li><b>Adresse :</b> <p>{{ profile.address|linebreaksbr }}</p></li>
  <li><b>Téléphone :</b> {{ profile.phone_number }}</li>
  <li><b>Adresse e-mail :</b> {{ profile.email }}</li>
  <li><b>Notes :</b> <p>{{ profile.notes|linebreaksbr }}</p></li>
</ul>

{% endblock %}

banking/templates/banking/admin/payment_detail.html
{% extends 'admin.html' %}

{% block breadcrumb %}
<li><a href="{% url 'payment-list' %}">Paiements</a></li>
<li class="active">{{ payment.payment_type_verbose }} {{ payment.reason }}</li>
{% endblock %}

{% load bootstrap4 %}

{% block content %}
<div class="panel panel-{{ payment.active|yesno:"success,danger,primary"}}">
    <div class="panel-heading">
        {% comment %}{% if perms.services.change_service %}
        <a class="btn btn-success pull-right" href="{% url 'service-edit' service.pk %}"><span class="glyphicon glyphicon-edit"></span>&nbsp;Éditer</a>
        {% endif %}
        {% endcomment %}
        <h4>{{ payment.payment_type_verbose }} {{ payment.reason }}</h4>
    </div>
    <div class="panel-body container">
        <div class="row">
            <div class="col-md-3 text-right"><strong>Type</strong></div>
            <div class="col-md-9">{{ payment.type_verbose }}</div>
        </div>
        {% if payment.type == payment.SERVICE %}
        <div class="row">
            <div class="col-md-3 text-right"><strong>Service</strong></div>
            <div class="col-md-9"><a href="{{ payment.reason.get_absolute_url }}">{{ payment.reason }}</a></div>
        </div>
        {% endif %}
        <div class="row">
            <div class="col-md-3 text-right"><strong>Adhérent·e</strong></div>
            <div class="col-md-9"><a href="{{ payment.get_adhesion.get_absolute_url }}">{{ payment.get_adhesion }}</a></div>
        </div>
        <div class="row">
            <div class="col-md-3 text-right"><strong>Période</strong></div>
            <div class="col-md-9">{{ payment.period_verbose }}</div>
        </div>
        {% if payment.period %}
        <div class="row">
            <div class="col-md-3 text-right"><strong>Status</strong></div>
            <div class="col-md-9">
                {% if payment.active %}
                en cours
                <a href="{% url 'payment-stop' payment.pk %}" class="btn btn-danger btn-xs">Stopper le paiement</a>
                {% else %}
                terminé
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 text-right"><strong>Premier paiement</strong></div>
            <div class="col-md-9">{{ payment.start }}</div>
        </div>
        {% if payment.end %}
        <div class="row">
            <div class="col-md-3 text-right"><strong>Dernier paiement</strong></div>
            <div class="col-md-9">{{ payment.end }}</div>
        </div>
        {% endif %}
        {% else %}
        <div class="row">
            <div class="col-md-3 text-right"><strong>Date du paiement</strong></div>
            <div class="col-md-9">{{ payment.start }}</div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

banking/templates/banking/admin/payment_form.html
{% extends 'admin.html' %}

{% block breadcrumb %}
<li><a href="{% url 'payment-list' %}">Paiements</a></li>
{% if reason %}
<li><a href="{{ reason.get_absolute_url }}">{{ reason }}</a></li>
{% endif %}
{% if payment %}
<li><a href="{{ payment.get_absolute_url }}">{{ payment }}</a></li>
<li class="active">Modification</li>
{% else %}
<li class="active">Nouveau</li>
{% endif %}
{% endblock %}

{% block content %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <h4>{% if payment %}Modifier{% else %}Ajouter{% endif %} un paiement</h4>
    </div>
    <div class="panel-body">
{% include '_form.html' %}
    </div>
</div>
{% endblock %}

banking/templates/banking/admin/payment_list.html
{% extends 'admin.html' %}

{% block breadcrumb %}
<li class="active">Paiements</li>
{% endblock %}

{% load bootstrap4 %}

{% block content %}
<div class="panel panel-primary">
    <div class="panel-heading">
        {% comment %}<a class="btn btn-success pull-right" href="{% url 'service-add' %}">Ajouter une cotisation</a>{% endcomment %}
        <h4>Liste des paiements</h4>
    </div>
    {% for payment in object_list %}
    {% if forloop.first %}
    <table class="table">
        <tr>
            <th>#</th>
            <th>Type</th>
            <th>Objet</th>
            <th>Montant</th>
        </tr>
    {% endif %}
        <tr class="{{ payment.active|yesno:"success,danger," }}">
            <td><a href="{{ payment.get_absolute_url }}">#{{ payment.pk }}</a></td>
            <td>{{ payment.type_verbose }}</td>
            <td><a href="{{ payment.reason.get_absolute_url }}">{{ payment.reason }}</a></td>
            <td>{{ payment }}</td>
        </tr>
    {% if forloop.last %}
    </table>
    {% endif %}
    {% empty %}
    <div class="panel-body">
        <em>Aucun paiement.</em>
    </div>
    {% endfor %}
</div>

<div class="text-center">
    {% bootstrap_pagination page_obj %}
</div>
{% endblock %}