djadhere/urls.py
from django.conf import settings
from django.contrib.gis import admin
from django.urls import include, path

urlpatterns = [
    path("accounts/", include("accounts.urls")),
    path("todo/", include("todo.urls")),
    path("", include("services.urls")),
    path("", include("adhesions.urls")),
    path("", include("banking.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]


admin.site.site_title = settings.SITE_TITLE
admin.site.site_header = settings.SITE_HEADER

todo/urls.py
from django.urls import path

from . import views

app_name = "todo"


urlpatterns = [
    path("", views.tasklist_list, name="list-tasklists"),
    path("<str:tasklist_slug>/", views.tasklist_detail, name="show-tasklist"),
    path(
        "<str:tasklist_slug>/completed/",
        views.tasklist_detail,
        {"completed": True},
        name="show-tasklist-completed",
    ),
    path(
        "<str:tasklist_slug>/reorder/",
        views.tasklist_reorder,
        name="reorder-tasklist",
    ),
    path(
        "<str:tasklist_slug>/subscribe/",
        views.tasklist_subscribe,
        {"subscribe": True},
        name="subscribe-tasklist",
    ),
    path(
        "<str:tasklist_slug>/unsubscribe/",
        views.tasklist_subscribe,
        {"subscribe": False},
        name="unsubscribe-tasklist",
    ),
    path("<str:tasklist_slug>/add/", views.task_form, name="add-task"),
    path("<str:tasklist_slug>/<int:task_id>/", views.task_detail, name="show-task"),
    path(
        "<str:tasklist_slug>/<int:task_id>/toggle-done/",
        views.task_toggle_done,
        name="toggle-task-done",
    ),
    path(
        "<str:tasklist_slug>/<int:task_id>/subscribe/",
        views.task_subscribe,
        {"subscribe": True},
        name="subscribe-task",
    ),
    path(
        "<str:tasklist_slug>/<int:task_id>/unsubscribe/",
        views.task_subscribe,
        {"subscribe": False},
        name="unsubscribe-task",
    ),
    path("<str:tasklist_slug>/<int:task_id>/edit/", views.task_form, name="edit-task"),
    path(
        "<str:tasklist_slug>/<int:task_id>/delete/",
        views.task_delete,
        name="delete-task",
    ),
]

todo/models.py
import datetime
import textwrap

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.db import models
from django.db.models import Q
from django.utils import timezone


class TaskList(models.Model):
    name = models.CharField(max_length=60, verbose_name="nom")
    slug = models.SlugField(null=False, blank=False, unique=True)
    groups = models.ManyToManyField(Group, verbose_name="groupe", blank=True)
    subscribers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name="subscribed_tasklists",
    )

    @property
    def completed_task_set(self):
        return self.task_set.filter(completed_date__isnull=False)

    @property
    def uncompleted_task_set(self):
        return self.task_set.filter(completed_date__isnull=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name = "liste de tâches"
        verbose_name_plural = "listes de tâches"


class Task(models.Model):
    title = models.CharField(max_length=140, verbose_name="titre")
    task_list = models.ForeignKey(TaskList, on_delete=models.PROTECT)
    created_date = models.DateField(default=timezone.now, blank=True, null=True)
    due_date = models.DateField(blank=True, null=True, verbose_name="due pour le")
    completed_date = models.DateField(blank=True, null=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="created_task_set",
        verbose_name="créée par",
    )
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="assigned_task_set",
        verbose_name="assignée à",
    )
    note = models.TextField(blank=True)
    priority = models.PositiveIntegerField(blank=True, null=True)
    subscribers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name="subscribed_tasks",
    )
    unsubscribers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name="unsubscribed_tasks",
    )

    def subscribed(self, user):
        if user in self.task_list.subscribers.all():
            return user not in self.unsubscribers.all()
        return user in self.subscribers.all()

    @property
    def watchers(self):
        return (
            get_user_model()
            .objects.filter(
                (Q(subscribed_tasklists=self.task_list) & ~Q(unsubscribed_tasks=self))
                | (~Q(subscribed_tasklists=self.task_list) & Q(subscribed_tasks=self)),
            )
            .order_by("pk")
            .distinct("pk")
        )

    def overdue_status(self):
        "Returns whether the Tasks's due date has passed or not."
        if self.due_date and datetime.date.today() > self.due_date:
            return True
        return None

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["priority", "created_date"]
        verbose_name = "tâche"
        verbose_name_plural = "tâches"


class TaskComment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="comments")
    date = models.DateTimeField(default=timezone.now)
    body = models.TextField(blank=True)

    @property
    def snippet(self):
        body_snippet = textwrap.shorten(self.body, width=35, placeholder="...")
        return f"{self.author!s} - {body_snippet}..."

    def __str__(self):
        return self.snippet

todo/forms.py
from django import forms

from adhesions.models import User

from .models import Task, TaskComment


def get_label_from_instance(obj):
    return "ADT%d %s" % (
        obj.adhesion.id,
        str(obj.profile),
    )


class TaskForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        tasklist = kwargs.pop("tasklist")
        super().__init__(*args, **kwargs)
        if tasklist.groups.exists():
            members = User.objects.filter(groups__in=tasklist.groups.all())
        else:
            members = User.objects.all()
        members = members.order_by("adhesion__id")
        members = members.select_related("adhesion")
        self.fields["assigned_to"].queryset = members
        self.fields["assigned_to"].label_from_instance = get_label_from_instance

    class Meta:
        model = Task
        fields = (
            "title",
            "note",
            "due_date",
            "assigned_to",
        )
        widgets = {
            "due_date": forms.DateInput(attrs={"type": "date"}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = TaskComment
        fields = ("body",)

todo/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.http import require_POST

from .decorators import allowed_tasklist_required
from .email import send_comment_notification, send_task_notification
from .forms import CommentForm, TaskForm
from .models import Task, TaskList


@login_required
def tasklist_list(request):
    lists = TaskList.objects.all()
    if not request.user.is_superuser:
        lists = lists.filter(groups__in=request.user.groups.all())
    lists = lists.order_by("name")
    lists = lists.annotate(
        own_uncompleted_task_count=Count(
            "task",
            filter=Q(task__completed_date__isnull=True, task__assigned_to=request.user),
        ),
    )
    return render(
        request,
        "todo/tasklist_list.html",
        {
            "lists": lists,
            "task_count": Task.objects.filter(
                completed_date__isnull=True,
                task_list__in=lists,
            ).count(),
            "list_count": lists.count(),
        },
    )


@allowed_tasklist_required
def tasklist_detail(request, tasklist, completed=False):
    task_list = tasklist.task_set.filter(completed_date__isnull=not completed)
    return render(
        request,
        "todo/tasklist_detail.html",
        {
            "tasklist": tasklist,
            "task_list": task_list,
            "completed": completed,
        },
    )


@allowed_tasklist_required
def tasklist_reorder(request, tasklist):
    newtasklist = request.POST.getlist("tasktable[]")
    if newtasklist:
        # Re-prioritize each task in list
        i = 1
        for pk in newtasklist:
            try:
                task = Task.objects.get(task_list=tasklist, pk=pk)
                task.priority = i
                task.save()
                i += 1
            except Task.DoesNotExist:
                # Can occur if task is deleted behind the scenes during re-ordering.
                # Not easy to remove it from the UI without page refresh, but prevent
                # crash.
                pass
    # All views must return an httpresponse of some kind ... without this we get
    # error 500s in the log even though things look peachy in the browser.
    return HttpResponse(status=201)


@allowed_tasklist_required
def tasklist_subscribe(request, tasklist, subscribe):
    if subscribe:
        tasklist.subscribers.add(request.user)
    else:
        tasklist.subscribers.remove(request.user)
    return redirect(
        reverse("todo:show-tasklist", kwargs={"tasklist_slug": tasklist.slug}),
    )


@allowed_tasklist_required
def task_form(request, tasklist, task_id=None):
    if task_id:
        task = get_object_or_404(Task, task_list=tasklist, pk=task_id)
        redirect_url = reverse(
            "todo:show-task",
            kwargs={"tasklist_slug": tasklist.slug, "task_id": task.pk},
        )
    else:
        task = None
        redirect_url = reverse(
            "todo:show-tasklist",
            kwargs={"tasklist_slug": tasklist.slug},
        )
    form = TaskForm(request.POST or None, tasklist=tasklist, instance=task)
    if request.method == "POST" and form.is_valid():
        if task:
            task = form.save()
            task.subscribers.add(request.user)
            if task.assigned_to and task.assigned_to not in task.unsubscribers.all():
                task.subscribers.add(task.assigned_to)
            send_task_notification(task, request.user, created=False)
            messages.success(request, "Tâche mise à jour avec succès.")
        else:
            task = form.save(commit=False)
            task.task_list = tasklist
            task.created_by = request.user
            task.save()
            task.subscribers.add(request.user)
            if task.assigned_to and task.assigned_to not in task.unsubscribers.all():
                task.subscribers.add(task.assigned_to)
            send_task_notification(task, request.user, created=True)
            messages.success(request, "Tâche créée avec succès.")
        return redirect(redirect_url)
    return render(
        request,
        "todo/task_form.html",
        {
            "tasklist": tasklist,
            "task": task,
            "form": form,
            "cancel_url": redirect_url,
        },
    )


@allowed_tasklist_required
def task_detail(request, tasklist, task_id):
    task = get_object_or_404(Task, task_list=tasklist, pk=task_id)
    form = CommentForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        comment = form.save(commit=False)
        comment.task = task
        comment.author = request.user
        comment.save()
        task.subscribers.add(request.user)
        send_comment_notification(comment, request.user)
        messages.success(request, "Commentaire ajouté avec succès.")
        return redirect(
            reverse(
                "todo:show-task",
                kwargs={"tasklist_slug": tasklist.slug, "task_id": task_id},
            ),
        )
    return render(
        request,
        "todo/task_detail.html",
        {
            "tasklist": tasklist,
            "task": task,
            "form": form,
            "subscribed": task.subscribed(request.user),
        },
    )


@allowed_tasklist_required
def task_toggle_done(request, tasklist, task_id):
    task = get_object_or_404(Task, task_list=tasklist, pk=task_id)
    if task.completed_date:
        task.completed_date = None
        messages.success(request, f"La tâche « {task.title} » a été marquée en cours.")
    else:
        task.completed_date = timezone.now()
        messages.success(request, f"La tâche « {task.title} » a été marquée complétée.")
    task.save()
    return redirect(
        reverse(
            "todo:show-task",
            kwargs={"tasklist_slug": tasklist.slug, "task_id": task_id},
        ),
    )


@allowed_tasklist_required
def task_subscribe(request, tasklist, task_id, subscribe):
    task = get_object_or_404(Task, task_list=tasklist, pk=task_id)
    if subscribe:
        task.unsubscribers.remove(request.user)
        # if request.user not in tasklist.subscribers.all():
        task.subscribers.add(request.user)
    else:
        task.subscribers.remove(request.user)
        # if request.user in tasklist.subscribers.all():
        task.unsubscribers.add(request.user)
    return redirect(
        reverse(
            "todo:show-task",
            kwargs={"tasklist_slug": tasklist.slug, "task_id": task_id},
        ),
    )


# TODO: are you sure?
@require_POST
@allowed_tasklist_required
def task_delete(request, tasklist, task_id):
    task = get_object_or_404(Task, task_list=tasklist, pk=task_id)
    task.delete()
    messages.success(request, f"La tâche « {task.title} » a été supprimée.")
    return redirect(
        reverse("todo:show-tasklist", kwargs={"tasklist_slug": tasklist.slug}),
    )

todo/templates/todo/base.html
{% extends "base.html" %}

{% block todotab %} active{% endblock %}

todo/templates/todo/task_detail.html
{% extends "todo/base.html" %}
{% load bootstrap4 %}

{% block content %}
  <div class="card-deck">
    <div class="card col-sm-8">
      <div class="card-body">
        <h3 class="card-title">{{ task.title }}</h3>
        {% if task.note %}
        <div class="card-text">{{ task.note|safe|urlize|linebreaks }}</div>
        {% endif %}
      </div>
    </div>

    <div class="card col-sm-4 p-0">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <a href="{% url 'todo:edit-task' tasklist.slug task.id %}" class="btn btn-sm btn-primary">
            <span class="fas fa-pen"></span>&nbsp;Éditer
          </a>

          <form method="post" action="{% url "todo:toggle-task-done" tasklist.slug task.id %}" role="form" class="d-inline">
            {% csrf_token %}
            <div style="display:inline;">
              {% if task.completed_date %}
              <button class="btn btn-danger btn-sm" type="submit" name="toggle_done">
                <span class="far fa-square"></span>&nbsp;Non terminée
              </button>
              {% else %}
              <button class="btn btn-success btn-sm" type="submit" name="toggle_done">
                <span class="far fa-check-square"></span>&nbsp;Terminée
              </button>
              {% endif %}
            </div>
          </form>

          {% if subscribed %}
          <a href="{% url 'todo:unsubscribe-task' tasklist.slug task.id %}" class="btn btn-sm btn-secondary">
            <span class="fas fa-eye-slash"></span>&nbsp;Se désabonner
          </a>
          {% else %}
          <a href="{% url 'todo:subscribe-task' tasklist.slug task.id %}" class="btn btn-sm btn-secondary">
            <span class="fas fa-eye"></span>&nbsp;S’abonner
          </a>
          {% endif %}

          {% comment %}
          <form method="post" action="{% url "todo:delete-task" tasklist.slug task.id %}" role="form" class="d-inline">
            {% csrf_token %}
            <div style="display:inline;">
              <button class="btn btn-danger btn-sm" type="submit" name="submit_delete">
                Supprimer
              </button>
            </div>
          </form>
          {% endcomment %}
        </li>
        <li class="list-group-item">
          <strong>Assignée à :</strong>
          {% if task.assigned_to %}{{ task.assigned_to.profile }}{% else %}–{% endif %}
        </li>
        <li class="list-group-item">
          <strong>Créée par :</strong> {{ task.created_by.profile }}
        </li>
        <li class="list-group-item">
          <strong>Due pour le :</strong>
          {% if task.overdue_status %}
          <span class="text-danger">{{ task.due_date|default:"–" }}</span>
          {% else %}
          {{ task.due_date|default:"–" }}
          {% endif %}
        </li>
        <li class="list-group-item">
          <strong>Terminée le :</strong> {{ task.completed_date|default:"–" }}
        </li>
        <li class="list-group-item">
          <strong>Dans la liste :</strong>
          {% if task.completed_date %}
          <a href="{% url 'todo:show-tasklist-completed' tasklist.slug %}">{{ task.task_list }}</a>
          {% else %}
          <a href="{% url 'todo:show-tasklist' tasklist.slug %}">{{ task.task_list }}</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>

  <div class="task_comments mt-4">
    {% if task.comments.exists %}
      <h5>Commentaires</h5>
      {% for comment in task.comments.all %}
      <div class="mb-3 card">
        <div class="card-header">
          <div class="float-left">
            {{ comment.author }}
          </div>
          <span class="float-right d-inline-block text-muted">
            {{ comment.date|date:"F d Y P" }}
          </span>
        </div>
        <div class="card-body">
          {{ comment.body|safe|urlize|linebreaks }}
        </div>
      </div>
      {% endfor %}
    {% else %}
        <h5>Pas de commentaire</h5>
    {% endif %}
  </div>

  <div class="mt-3">
    <h5>Ajouter un commentaire</h5>
    <form action="" method="post">
      {% csrf_token %}
      <div class="form-group">
        <textarea name="body" rows="3" class="form-control" title="" id="id_body"></textarea>
      </div>
      <input class="btn btn-sm btn-primary" type="submit" name="add_comment" value="Ajouter un commentaire">
    </form>
  </div>
{% endblock %}

todo/templates/todo/task_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block todotab %} active{% endblock %}

{% block extrahead %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('#id_assigned_to').select2();
});
</script>
{% endblock %}

{% block content %}
  <h1>{% if task %}Modifier{% else %}Ajouter{% endif %} une tâche</h1>

  <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    {% if task %}
    {% bootstrap_button "Modifier" button_type="submit" button_class="btn-primary" %}
    {% else %}
    {% bootstrap_button "Ajouter" button_type="submit" button_class="btn-primary" %}
    {% endif %}
    {% bootstrap_button "Annuler" button_type="link" href=cancel_url %}
    {% endbuttons %}
  </form>

{% endblock %}

todo/templates/todo/tasklist_detail.html
{% extends "todo/base.html" %}

{% block content %}

  <a href="{% url 'todo:add-task' tasklist.slug %}" class="btn btn-primary">
    <span class="fas fa-plus"></span>&nbsp;Ajouter une tâche
  </a>
  {% if request.user in tasklist.subscribers.all %}
  <a href="{% url 'todo:unsubscribe-tasklist' tasklist.slug %}" class="btn btn-secondary">
    <span class="fas fa-eye-slash"></span>&nbsp;Se désabonner des notifications
  </a>
  {% else %}
  <a href="{% url 'todo:subscribe-tasklist' tasklist.slug %}" class="btn btn-secondary">
    <span class="fas fa-eye"></span>&nbsp;S’abonner aux notifications
  </a>
  {% endif %}
  <hr />

  {% if task_list %}
      {% if completed %}
      <h1>Tâches terminées de la liste « {{ tasklist.name }} »</h1>
      {% else %}
      <h1>Tâches de la liste « {{ tasklist.name }} »</h1>
      <p><small><i>Faites glisser les tâches pour définir les priorités.</i></small></p>
      {% endif %}

      <table class="table" id="tasktable">
        <tr class="nodrop">
          <th scope="col">Tâche</th>
          <th scope="col">Créé le</th>
          {% if completed %}
          <th scope="col">Terminée le</th>
          {% else %}
          <th scope="col">Due pour le</th>
          {% endif %}
          <th scope="col">Créé par</th>
          <th scope="col">Assigné à</th>
          <th scope="col"></th>
          {% comment %}<th>Mark</th{% endcomment %}
        </tr>

        {% for task in task_list %}
          <tr id="{{ task.id }}">
            <td>
                <a href="{% url 'todo:show-task' tasklist.slug task.id %}">{{ task.title|truncatewords:10 }}</a>
              {% if request.user in task.task_list.subscribers.all and request.user in task.unsubscribers.all %}
              <span class="float-right badge badge-secondary badge-pill"><span class="far fa-eye-slash"></span></span>
              {% elif request.user not in task.task_list.subscribers.all and request.user in task.subscribers.all %}
              <span class="float-right badge badge-secondary badge-pill"><span class="far fa-eye"></span></span>
              {% endif %}
            </td>
            <td>
                {{ task.created_date|date:"m/d/Y" }}
            </td>
            <td>
              <span{% if task.overdue_status %} class="text-danger"{% endif %}>
                {{ task.due_date|date:"m/d/Y"|default:"–" }}
              </span>
            </td>
            <td>
              {{ task.created_by }}
            </td>
            <td>
              {% if task.assigned_to %}{{ task.assigned_to }}{% else %}–{% endif %}
            </td>
            {% comment %}
            <td>
              <form method="post" action="{% url "todo:task_toggle_done" task.id %}" role="form">
                {% csrf_token %}
                <button class="btn btn-info btn-sm" type="submit" name="toggle_done">
                  {% if view_completed %}
                    Not Done
                  {% else %}
                    Done
                  {% endif %}
                </button>
              </form>
            </td>
            {% endcomment %}
            <td>
            </td>
          </tr>
        {% endfor %}
      </table>

  {% else %}
    <h4>Aucune tâche {% if completed %}terminée{% else %}en cours{% endif %} dans la liste « {{ tasklist.name }} ».</h4>
  {% endif %}

  {% if completed %}
  <a href="{% url 'todo:show-tasklist' tasklist.slug %}" class="btn btn-info">Voir les tâches non terminées</a>
  {% else %}
  <a href="{% url 'todo:show-tasklist-completed' tasklist.slug %}" class="btn btn-info">Voir les tâches terminées</a>
  {% endif %}

{% endblock %}

{% block extra_js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/TableDnD/0.9.1/jquery.tablednd.js" integrity="sha256-d3rtug+Hg1GZPB7Y/yTcRixO/wlI78+2m08tosoRn7A=" crossorigin="anonymous"></script>

  <script type="text/javascript">
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    function order_tasks(data) {
      // The JQuery plugin tableDnD provides a serialize() function which provides the re-ordered
      // data in a list. We pass that list as an object ("data") to a Django view
      // to save new priorities on each task in the list.
      $.ajax({
          url: "{% url 'todo:reorder-tasklist' tasklist.slug %}",
          type: "post",
          headers: {
              "X-CSRFToken": csrftoken
          },
          data: data,
          dataType: "json"
      });
      return false;
    };

    $(document).ready(function() {
      // Initialise the task table for drag/drop re-ordering
      $('#tasktable').tableDnD({
        onDrop: function(table, row) {
          order_tasks($.tableDnD.serialize());
        }
      });

    });
  </script>
{% endblock extra_js %}

todo/templates/todo/tasklist_list.html
{% extends "todo/base.html" %}

{% block js_end %}
{{ block.super }}
<script type="text/javascript">
$(function () {
      $('[data-toggle="tooltip"]').tooltip()
})
</script>
{% endblock %}

{% block content %}
  <h1>Liste des tâches</h1>

  <p>{{ task_count }} tâche{{ task_count|pluralize }} en cours dans {{ list_count }} liste{{ list_count|pluralize }}</p>

  <ul class="list-group mb-4">
    {% for list in lists %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <a href="{% url 'todo:show-tasklist' list.slug %}">{{ list.name }}</a>
      <span class="text-right">
        {% if request.user in list.subscribers.all %}
        <span class="badge badge-secondary badge-pill" data-toggle="tooltip" data-placement="top" title="Vous êtes abonné aux notifications concernant les tâches de cette liste.">
          <span class="far fa-eye"></span>
        </span>
        {% endif %}
        {% if list.own_uncompleted_task_count %}
        <span class="badge badge-danger badge-pill" data-toggle="tooltip" data-placement="top" title="Nombre de tâches qui vous est assignées.">
          {{ list.own_uncompleted_task_count }}
        </span>
        {% endif %}
        <span class="badge badge-primary badge-pill" data-toggle="tooltip" data-placement="top" title="Nombre de tâches dans cette liste.">
          {{ list.uncompleted_task_set.count }}
        </span>
      </span>
    </li>
    {% endfor %}
  </ul>

{% endblock %}